### PR TITLE
Home Page with magic menus

### PR DESCRIPTION
**Pull request by johnwalkervinest**
This is the home page layout. It follows the wireframe model we devised at the field open day.
I have added functionality so the second navigation bar does not scroll out of view.
Remember to sign in before menu items will become visible on the navigation bar.
Please clone this into a new directory and do vagrant up.
All comments welcome.
John

### CODE REVIEW

**Comment by bsimpson53** [comment]
Hi John,

Sorry I didn't see this work! I've had a brief look through and I've got a few comments but it'll take a little time to put them together.

Ben

**Comment by johnwalkervinest** [comment]
Hi Ben,
I'm not happy with it! I need to make some changes. Athough it does work when I run it. I nned a better approach to making menu bars.

**Comment by bsimpson53** [comment]
I'm wrestling with ghost at the mo but when I've nailed that I'll have a
closet look.

**Comment by johnwalkervinest** [comment]
Hello,
I made some change to this, to tidy up the code.

**Comment by bsimpson53** [comment]
Cool. Have almost finished the ghost stuff so will merge then together.

**Comment by bsimpson53** [comment]
Hi @johnwalkervinest 

The magic scrolling stuff works great :)

I've started to merge this, I notice that you're using angular-strap, however angular-bootstrap is already included, so I think it would be better to use that. I'll probably just change it as I work through it.

Now that I have support for ghost built in I can hook the content into the relevant pages.

Let me know if you're keen to have a bash :)

**Comment by bsimpson53** [comment]
I've manually merged this and used it to inspire the final version, I'm pretty happy with the results, thanks for the work John!

**Pull request closed without merging**
